name: Publish to Packagist

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Packagist
        uses: packagist/publish@v1
        with:
          package-name: mrnaeem4/ci4-request-analysis
          username: ${{ secrets.PACKAGIST_USERNAME }}
          token: ${{ secrets.PACKAGIST_TOKEN }}
